image: localhost:5000/render_image

variables:
  GIT_SUBMODULE_STRATEGY: recursive


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build
    - test_data

stages:
  - init_and_build
  - test
  - latex
  
init_and_build:
  stage: init_and_build
  script:
    - git submodule update --init --recursive
    - apt-get install -y python3-dev python2-dev python-pip python3-numpy libboost-all-dev
    - pip2 install numpy
    - git clone https://gitlab.tuwien.ac.at/e193-02-rendering-course/rendering-data.git test_data
    - cmake . -Bbuild
    - cd build
    - make -j8
    - cd ..
  allow_failure: false


testing0:
  stage: test
  script:
    - cp -r ./test_data/assignment0/* .
    - python3 run_tests.py
  tags:
    - rendering
  only:
    - submission0
  allow_failure: false
  artifacts:
    paths: 
      - ./*.png
      - ./*.csv
      - report.tex
    expire_in: 1 d

testing1:
  stage: test
  script:
    - cp -r ./test_data/assignment1/* .
    - python3 run_tests.py
  tags:
    - rendering
  only:
    - submission1
  allow_failure: false
  artifacts:
    paths: 
      - ./*.png
      - ./*.csv
      - report.tex
    expire_in: 1 d

testing2:
  stage: test
  script:
    - cp -r ./test_data/assignment2/* .
    - python3 run_tests.py
  tags:
    - rendering
  only:
    - submission2
  allow_failure: false
  artifacts:
    paths: 
      - ./*.png
      - ./*.csv
      - report.tex
    expire_in: 1 d

testing3:
  stage: test
  script:
    - cp -r ./test_data/assignment3/* .
    - python3 run_tests.py
  tags:
    - rendering
  only:
    - submission3
  allow_failure: false
  artifacts:
    paths: 
      - ./*.png
      - ./*.csv
      - report.tex
    expire_in: 1 d

report:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  stage: latex
  image: localhost:5000/tex_image
  script:
    - pdflatex report.tex
  tags:
    - latex-minimal
  only:
    - submission0
    - submission1
    - submission2
    - submission3
  allow_failure: false
  artifacts:
    paths: 
      - report.pdf
    expire_in: 1 d
